default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  user: <%= ENV['USER'] %>
  password:
  host: localhost

development:
  <<: *default
  database: ppau-motion_development
  min_messages: notice

test:
  <<: *default
  database: ppau-motion_test

production:
  url: <%= ENV["DATABASE_URL"] %>
